name: Build APK

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build_droid:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies and build APK
      run: |
        sudo apt update
        sudo apt install -y \
          build-essential ccache libffi-dev libssl-dev libsqlite3-dev \
          libjpeg-dev zlib1g-dev libfreetype6-dev \
          git unzip openjdk-17-jdk python3-pip

        pip install --upgrade pip
        pip install cython buildozer

        buildozer android debug
