name: Build APK

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build_droid:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies and build APK
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk python3-pip \
            libfreetype6-dev libffi-dev libssl-dev \
            libsqlite3-dev libjpeg-dev zlib1g-dev \
            build-essential ccache

          pip install --upgrade pip
          pip install cython buildozer

          buildozer android debug
