name: Build APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build_droid:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          build-essential git zip unzip openjdk-17-jdk \
          python3-pip python3-setuptools python3-wheel \
          libffi-dev libssl-dev libjpeg-dev libfreetype6-dev \
          libsqlite3-dev zlib1g-dev

    - name: Install buildozer and Cython
      run: |
        pip install --upgrade pip
        pip install cython buildozer

    - name: Build APK
      run: |
        buildozer android debug
